### PR TITLE
Simplify classic

### PR DESCRIPTION
**Pull request by waveform80**
The "classic" branch currently *generates* the boot config for the various releases. This is a good example of something that is "too clever to be maintainable" and needs replacing with something much simpler. This branch removes all the horridly complex generation of configs from the `Makefile` and replaces them with trivial copy operations. The config template snippets are removed and replaced with a series of directories, the contents of which have been directly extracted from the corresponding images.

This branch also removes the "core" target from the "Makefile"; this branch can't build core gadgets and shouldn't pretend it can, and finally adds some brief documentation of the new layout of the "configs" directory.

### CODE REVIEW

**Comment by waveform80** [comment]
Open question: I've included the (now unsupported) interim releases in the "configs" directory not so that they can actually be generated, but more so one can track the evolution of the boot configuration over releases. However, it's arguable that these should just be excluded for further simplification.

Then again, we don't bother pruning unsupported branches from repos like lp:ubuntu-images so perhaps these should just stick around?

**Comment by vorlonofportland** [comment]
> Then again, we don't bother pruning unsupported branches from repos like lp:ubuntu-images so perhaps these should just stick around?

I think keeping around legacy branches for EOLed releases is very different than keeping such things in your working directory.  In other similar projects (debian-cd, ubuntu-cdimage) we do take care to prune content specific to releases when they go EOL.  I would like to see the same here.

**Comment by waveform80** [comment]
Fair enough; EOL releases removed

**Comment by waveform80** [comment]
@vorlonofportland any other objections? I'd like to get this merged so I can do some "official" test builds of the gnome-initial-setup oracular images

**Pull request merged**
