### PR TITLE
improve readme to explain building in a container

### PR DESCRIPTION
**Pull request by stulluk**

### CODE REVIEW

**Comment by anonymouse64** [comment]
Have you tried letting snapcraft manage the LXD container for you via `SNAPCRAFT_BUILD_ENVIRONMENT=lxd snapcraft --enable-experimental-package-repositories` ? That should work, it's how we build it in Travis CI and how other developers built it locally too

**Comment by stulluk** [comment]
> Have you tried letting snapcraft manage the LXD container for you via `SNAPCRAFT_BUILD_ENVIRONMENT=lxd snapcraft --enable-experimental-package-repositories` ? That should work, it's how we build it in Travis CI and how other developers built it locally too

Thank you ! This simplified explanation a lot. Do you have any other suggestions to improve ?

**Comment by anonymouse64** [comment]
What you have is reasonable, but if you want to have more eyes on it, I would recommend @degville to also take a look here

**Review by degville — COMMENTED** [review]
Thanks for submitting this, and you're right in that this doc definitely needs updating. Snapcraft (on its own) defaults to building with a Multipass container but LXD often performs better, especially with repeated builds. I think this is worth mentioning but not necessarily fully endorsing.

I think we should just have a single "Building" section describing the default build method and mentioning both LXD and `--destructive-mode` as other options (and pointing out the danger of the later). I'm happy to update this doc with the above, if that's easier.

**Comment by degville** [comment]
I've incorporated @stulluk's suggestions, along with a few more fixes, into #75.

**Comment by stulluk** [comment]
> I've incorporated @stulluk's suggestions, along with a few more fixes, into #75.

I believe it is better to close this PR, how do you think ?

**Pull request closed without merging**
