### PR TITLE
Enable mir-kiosk to start on Ubuntu Core 18/RPi 3

### LINKED ISSUE #779: Mir does not start on Ubuntu Core 18/RPi 3
This affects `mir-kiosk`, but is best documented using `mir-test-tools`:

Install `mir-test-tools` and run:
```bash
sudo snap run mir-test-tools.bash
```
Then run:
```
mir_demo_server
```
Expect: server starts
Actual: server hangs after message "mirserver: Starting"

This only happens the first time, so press Ctrl+C and try again
```
mir_demo_server
```
This time the server starts.

The server is hung somewhere in the virtual terminal setup - and if you switch to VT4 while it is hung it will continue to a normal startup.

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Enable mir-kiosk to start on Ubuntu Core 18/RPi 3. (Fixes https://github.com/MirServer/mir/issues/779)

### CODE REVIEW

**Review by ogra1 — APPROVED** [review]
looks fine

**Comment by liqdfire** [comment]
Would this impact psplash? The README specifically refers to removing that command line option as part of disabling psplash.

**Comment by xnox** [comment]
Ideally, we should not be using vt.handoff anywhere at all anymore, and default to booting on vt1 everywhere in ubuntu.

I don't know what psplash is, nor can comment on how that is affected.

**Comment by ogra1** [comment]
> Would this impact psplash? The README specifically refers to removing that command line option as part of disabling psplash.

no, psplash runs before the vt change happens 

@xnox psplash is a very minimal boot splash (originally used by yocto) that most of our digital signage customers use in their gadgets to show an image before content comes up during boot. (see: https://github.com/ogra1/pi-kiosk-gadget/ )

**Comment by AlanGriffiths** [comment]
Can this land yet?

**Comment by xnox** [comment]
need conflict resolutions but yes this should land.

**Comment by AlanGriffiths** [comment]
> need conflict resolutions but yes this should land.

Done

**Pull request merged**
